version: '2'

services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    links:
      - db
      - redis
    ports:
      - '80:80'

  db:
    image: mysql:5.5
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'

  redis:
    image: redis:3.0
